server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/report?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: liumx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml